<?php


namespace Pinto;

/**
 * @var callable $dump
 * @var bool $showEnvironment
 * @var array $obStatus
 * @var BlueScreen $this
 */

if (!$showEnvironment) {
	return;
}

$constants = get_defined_constants(true)['user'] ?? [];
?>
<section class="Pinto-section">
	<h2 class="Pinto-section-label"><a href="#" data-Pinto-ref="^+" class="Pinto-toggle Pinto-collapsed">Environment</a></h2>

	<div class="Pinto-section-panel Pinto-collapsed">

	<div class="Pinto-tabs">
		<ul class="Pinto-tab-bar">
			<li class="Pinto-tab-label Pinto-active"><a href="#">$_SERVER</a></li>
<?php if ($_SESSION ?? null): ?>
			<li class="Pinto-tab-label"><a href="#">$_SESSION</a></li>
<?php endif ?>
<?php if ($constants): ?>
			<li class="Pinto-tab-label"><a href="#">Constants</a></li>
<?php endif ?>
			<li class="Pinto-tab-label"><a href="#">Configuration</a></li>
<?php if ($obStatus): ?>
			<li class="Pinto-tab-label"><a href="#">Output buffers</a></li>
<?php endif ?>

		</ul>


		<div>
			<div class="Pinto-tab-panel Pinto-pane Pinto-active">
				<table class="Pinto-sortable">
<?php foreach ($_SERVER as $k => $v): ?>
				<tr><th><?= Helpers::escapeHtml($k) ?></th><td><?= $dump($v, $k) ?></td></tr>
<?php endforeach ?>
				</table>
			</div>


<?php if ($_SESSION ?? null): ?>
			<div class="Pinto-tab-panel">
				<div class="Pinto-pane">
					<table class="Pinto-sortable">
<?php	foreach ($_SESSION as $k => $v): ?>
						<tr><th><?= Helpers::escapeHtml($k) ?></th><td><?= $k === '__NF' ? '<i>Nette Session</i>' : $dump($v, $k) ?></td></tr>
<?php	endforeach ?>
					</table>
				</div>


<?php if (!empty($_SESSION['__NF']['DATA'])):?>
				<h3>Nette Session</h3>
				<div class="Pinto-pane">
					<table class="Pinto-sortable">
<?php	foreach ($_SESSION['__NF']['DATA'] as $k => $v): ?>
						<tr><th><?= Helpers::escapeHtml($k) ?></th><td><?= $dump($v, $k) ?></td></tr>
<?php	endforeach ?>
					</table>
				</div>
<?php endif ?>
			</div>
<?php endif ?>



<?php if ($constants): ?>
			<div class="Pinto-tab-panel Pinto-pane">
				<table class="Pinto-sortable">
<?php	foreach ($constants as $k => $v): ?>
					<tr><th><?= Helpers::escapeHtml($k) ?></th><td><?= $dump($v, $k) ?></td></tr>
<?php	endforeach ?>
				</table>
			</div>
<?php endif ?>


			<div class="Pinto-tab-panel">
				<?php $this->renderPhpInfo() ?>

			</div>


<?php if ($obStatus): ?>
			<div class="Pinto-tab-panel Pinto-pane">
				<?= Dumper::toHtml($obStatus, [Dumper::COLLAPSE_COUNT => 10]) ?>
			</div>
<?php endif ?>
		</div>
	</div>
	</div>
</section>
