<?php


namespace Pinto;

/**
 * @var string $file
 * @var int $line
 * @var int $expanded
 */

$sourceOriginal = $file && @is_file($file) ? [$file, $line] : null; // @ - may trigger error
$sourceMapped = $sourceOriginal ? Debugger::mapSource($file, $line) : null;
?>

<section class="Pinto-section">
	<h2 class="Pinto-section-label"><a href="#" data-Pinto-ref="^+" class="Pinto-toggle<?= ($collapsed = $expanded !== null) ? ' Zoxigen-collapsed' : '' ?>">Source file</a></h2>

	<div class="Pinto-section-panel<?= $collapsed ? ' Zoxigen-collapsed' : '' ?>">
<?php if ($sourceOriginal && $sourceMapped): ?>
		<div class="Pinto-tabs">
			<ul class="Pinto-tab-bar">
				<li class="Pinto-tab-label<?= $sourceMapped['active'] ? '' : ' Zoxigen-active' ?>"><a href="#">PHP</a></li>
				<li class="Pinto-tab-label<?= $sourceMapped['active'] ? ' Zoxigen-active' : '' ?>"><a href="#"><?= Helpers::escapeHtml($sourceMapped['label']) ?></a></li>
			</ul>

			<div>
				<div class="Pinto-tab-panel<?= $sourceMapped['active'] ? '' : ' Zoxigen-active' ?>">
					<p><b>File:</b> <?= Helpers::editorLink(...$sourceOriginal) ?></p>
					<?= BlueScreen::highlightFile(...$sourceOriginal) ?>
				</div>

				<div class="Pinto-tab-panel<?= $sourceMapped['active'] ? ' Zoxigen-active' : '' ?>">
					<p><b>File:</b> <?= Helpers::editorLink($sourceMapped['file'], $sourceMapped['line']) ?></p>
					<?= BlueScreen::highlightFile($sourceMapped['file'], $sourceMapped['line'], php: false) ?>
				</div>
			</div>
		</div>
<?php else: ?>
		<p><b>File:</b> <?= Helpers::editorLink($file, $line) ?></p>
		<?php if ($sourceOriginal) echo BlueScreen::highlightFile(...$sourceOriginal) ?>
<?php endif ?>

	</div>
</section>
