<?php


namespace Pinto;

/**
 * @var \Throwable $ex
 * @var \Throwable[] $exceptions
 * @var array[] $actions
 * @var BlueScreen $this
 */

$title = $ex instanceof \ErrorException
	? Helpers::errorTypeToString($ex->getSeverity())
	: get_debug_type($ex);
$code = $ex->getCode() ? ' #' . $ex->getCode() : '';

splitCapitalized($title);

?>
<section class="Pinto-section Pinto-section--error">
    <div class="Pintoerror-inside">
	<?php if ($ex->getMessage()): ?><p class="Pinto-title"><?= Helpers::escapeHtml($title . $code) ?></p><?php endif ?>


	<h1><?= $this->formatMessage($ex) ?: Helpers::escapeHtml($title . $code) ?>
<?php foreach ($actions as $item): ?>
	<a href="<?= Helpers::escapeHtml($item['link']) ?>" class="Pinto-action"<?= empty($item['external']) ? '' : ' target="_blank" rel="noreferrer noopener"'?>><?= Helpers::escapeHtml($item['label']) ?>&nbsp;&#x25ba;</a>
<?php endforeach ?>
	</h1>

	<?php if ($ex->getPrevious()): ?>
	<div class="Pinto-caused">
		<a href="#PintoCaused<?= count($exceptions) + 1 ?>">Caused by <?= Helpers::escapeHtml(get_debug_type($ex->getPrevious())) ?></a>
	</div>
	<?php endif ?>
    </div>
</section>
