<?php


namespace Pinto;

/**
 * @var \Throwable $ex
 * @var \Throwable[] $exceptions
 * @var array[] $actions
 * @var callable $dump
 * @var BlueScreen $this
 * @var \Generator[] $generators
 * @var \Fiber[] $fibers
 */

?>
<?php require __DIR__ . '/section-header.phtml' ?>

<?php foreach ($this->renderPanels($ex) as $panel): ?>
<section class="Pinto-section">
	<h2 class="Pinto-section-label"><a href="#" data-Pinto-ref="^+" class="Pinto-toggle"><?= Helpers::escapeHtml($panel->tab) ?></a></h2>

	<div class="Pinto-section-panel">
		<?= $panel->panel ?>
	</div>
</section>
<?php endforeach ?>

<?php if (!$exceptions && ($generators || $fibers)): ?>
<section class="Pinto-section Pinto-section--stack">
	<div class="Pinto-section-panel">
		<div class="Pinto-tabs">
			<ul class="Pinto-tab-bar">
				<li class="Pinto-tab-label Pinto-active"><a href="#">Main thread</a></li>

				<?php foreach ($generators as $id => $generator): ?>
					<li class="Pinto-tab-label"><a href="#">Generator #<?= $id ?></a></li>
				<?php endforeach ?>

				<?php foreach ($fibers as $id => $fiber): ?>
					<li class="Pinto-tab-label"><a href="#">Fiber #<?= $id ?></a></li>
				<?php endforeach ?>
			</ul>

			<div>
				<div class="Pinto-tab-panel Pinto-active">
					<?php require __DIR__ . '/section-stack-exception.phtml' ?>
				</div>

				<?php foreach ($generators as $generator): ?>
					<div class="Pinto-tab-panel">
						<?php require __DIR__ . '/section-stack-generator.phtml' ?>
					</div>
				<?php endforeach ?>

				<?php foreach ($fibers as $fiber): ?>
					<div class="Pinto-tab-panel">
						<?php require __DIR__ . '/section-stack-fiber.phtml' ?>
					</div>
				<?php endforeach ?>
			</div>
		</div>
	</div>
</section>
<?php else: ?>
<?php require __DIR__ . '/section-stack-exception.phtml' ?>
<?php endif ?>

<?php require __DIR__ . '/section-exception-exception.phtml' ?>

<?php require __DIR__ . '/section-exception-causedBy.phtml' ?>
