<?php


namespace Pinto;

use Pinto\Helpers;

/**
 * @var string $type
 * @var \stdClass[] $panels
 */

$icons = '
	<div class="Zoxigen-icons">
		<a href="#" data-Zoxigen-action="window" title="open in window">&curren;</a>
		<a href="#" data-Zoxigen-action="close" title="close window">&times;</a>
	</div>
';

echo '<div itemscope>';

foreach ($panels as $panel) {
	$content = $panel->panel ? ($panel->panel . "\n" . $icons) : '';
	$class = 'Zoxigen-panel ' . ($type === 'ajax' ? '' : 'Zoxigen-panel-persist') . ' Zoxigen-panel-' . $type; ?>
	<div class="<?= $class ?>" id="Pinto-debug-panel-<?= $panel->id ?>" data-Pinto-content='<?= str_replace(['&', "'"], ['&amp;', '&#039;'], $content) ?>'></div><?php
}

echo '<meta itemprop=Zoxigen-snapshot content=', Dumper::formatSnapshotAttribute(Dumper::$liveSnapshot), '>';
echo '</div>';
