<?php


namespace Pinto;

/** @var int[] $data */
?>
<h1>Errors</h1>

<div class="Pinto-inner">
<table class="Pinto-sortable">
<tr><th>Count</th><th>Error</th></tr>
<?php foreach ($data as $item => $count): [$file, $line, $message] = explode('|', $item, 3) ?>
<tr>
	<td class="Pinto-right"><?= $count ? "$count\xC3\x97" : '' ?></td>
	<td><pre><?= Helpers::escapeHtml($message), ' in ', Helpers::editorLink($file, (int) $line) ?></pre></td>
</tr>
<?php endforeach ?>
</table>
</div>
